### ISSUE TITLE
This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String

### ISSUE THREAD

**Issue by ngeorgieff** [acjohnson/puppet-adcli#3]
<tt>
[root@puppet-dev ~]# puppet apply -t /etc/puppetlabs/code/environments/production/modules/adcli/examples/test.pp
Info: Loading facts
Info: Loading facts
**Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README.** at ["/etc/puppetlabs/code/environments/production/modules/adcli/manifests/init.pp", 51]:
   (at /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /etc/puppetlabs/puppet/hiera.yaml)
<tt>

**Comment by acjohnson** [comment]
resolved by 25c52dbb1d4999f0cc77fedfa28edc5a419e3c48
