### ISSUE TITLE
Issues with Puppet 3?

### ISSUE THREAD

**Issue by mimmus** [acjohnson/puppet-adcli#7]
Hi,
I'm trying this module on a (quite old) Red Hat Satellite server with Puppet 3 but I'm getting:
`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Unknown function validate_legacy at /etc/puppet/environments/.../modules/adcli/manifests/init.pp:51 on node...
`
Peraphs, is my Puppet too old?

Thanks

**Comment by acjohnson** [comment]
It sounds like you are trying to run this module on an pre Puppet 4.x installation. This module uses the `validate_legacy` function in Puppet 4 `stdlib`. Read more about it here: https://puppet.com/blog/ntp-puppet-4-language-update

You should be able to install Ruby Version Manager (https://rvm.io) though and then install the latest puppet gem into your RVM environment if you want to run this module that badly.
